// geeting all the spans in that story paragraphs
let noun1user = document.querySelector("#userNoun1");
let noun2user = document.querySelector("#userNoun2");
let adj1user = document.querySelector("#userAdj1");
let adj2user = document.querySelector("#userAdj2");
let actuser = document.querySelector("#userAct");
let verbuser = document.querySelector("#userVerb");
let occationuser = document.querySelector("#specialDay");

let uniInputs = document.querySelectorAll(".unistory");
// buttonss
const clearbtn = document.querySelector(".clear");
const displaybtn = document.querySelector(".story");
const randombtn = document.querySelector(".rand");
const backbtn = document.querySelector(".back");

// story paragraph element
const storyPara = document.querySelector(".storypara");
// input field section
const enterWords = document.querySelector(".enterwords");

// error showing elements
const errorr = document.querySelector(".error");
const btnCloseError = document.querySelector(".error-close");
const overlayClick = document.querySelector(".overlay");
const badMsg = document.querySelector(".errorMsg");

// this is the function which can clear all the inputs on the page
function clearAllInputs() {
  for (let i = 0; i < uniInputs.length; i++) {
    uniInputs[i].value = "";
  }
}
clearbtn.addEventListener("click", clearAllInputs);

displaybtn.addEventListener("click", function () {
  let count = 0;
  for (let i = 0; i < uniInputs.length; i++) {
    if (uniInputs[i].value == "") {
      count++;
    }
  }
  //   this is if user left any field unentered
  if (count > 0) {
    errorr.classList.remove("hidden");
    overlayClick.classList.remove("hidden");
    badMsg.textContent = "Please enter all the fields.";
  }
  //   this section is if user enter all the required fields
  else {
    //   entering the user entered words

    // text fields data
    let noun1txt = document.querySelector("#noun1").value;
    let noun2txt = document.querySelector("#noun2").value;
    let adj1txt = document.querySelector("#adj1").value;
    let adj2txt = document.querySelector("#adj2").value;
    let acttxt = document.querySelector("#act").value;
    let verbtxt = document.querySelector("#verb").value;
    let occationtxt = document.querySelector("#occation").value;

    const badWords = [
      "4r5e",
      "5h1t",
      "5hit",
      "a55",
      "anal",
      "anus",
      "ar5e",
      "arrse",
      "arse",
      "ass",
      "ass-fucker",
      "asses",
      "assfucker",
      "assfukka",
      "asshole",
      "assholes",
      "asswhole",
      "a_s_s",
      "b!tch",
      "b00bs",
      "b17ch",
      "b1tch",
      "ballbag",
      "balls",
      "ballsack",
      "bastard",
      "beastial",
      "beastiality",
      "bellend",
      "bestial",
      "bestiality",
      "bi+ch",
      "biatch",
      "bitch",
      "bitcher",
      "bitchers",
      "bitches",
      "bitchin",
      "bitching",
      "bloody",
      "blow job",
      "blowjob",
      "blowjobs",
      "boiolas",
      "bollock",
      "bollok",
      "boner",
      "boob",
      "boobs",
      "booobs",
      "boooobs",
      "booooobs",
      "booooooobs",
      "breasts",
      "buceta",
      "bugger",
      "bum",
      "bunny fucker",
      "butt",
      "butthole",
      "buttmuch",
      "buttplug",
      "c0ck",
      "c0cksucker",
      "carpet muncher",
      "cawk",
      "chink",
      "cipa",
      "cl1t",
      "clit",
      "clitoris",
      "clits",
      "cnut",
      "cock",
      "cock-sucker",
      "cockface",
      "cockhead",
      "cockmunch",
      "cockmuncher",
      "cocks",
      "cocksuck",
      "cocksucked",
      "cocksucker",
      "cocksucking",
      "cocksucks",
      "cocksuka",
      "cocksukka",
      "cok",
      "cokmuncher",
      "coksucka",
      "coon",
      "cox",
      "crap",
      "cum",
      "cummer",
      "cumming",
      "cums",
      "cumshot",
      "cunilingus",
      "cunillingus",
      "cunnilingus",
      "cunt",
      "cuntlick",
      "cuntlicker",
      "cuntlicking",
      "cunts",
      "cyalis",
      "cyberfuc",
      "cyberfuck",
      "cyberfucked",
      "cyberfucker",
      "cyberfuckers",
      "cyberfucking",
      "d1ck",
      "damn",
      "dick",
      "dickhead",
      "dildo",
      "dildos",
      "dink",
      "dinks",
      "dirsa",
      "dlck",
      "dog-fucker",
      "doggin",
      "dogging",
      "donkeyribber",
      "doosh",
      "duche",
      "dyke",
      "ejaculate",
      "ejaculated",
      "ejaculates",
      "ejaculating",
      "ejaculatings",
      "ejaculation",
      "ejakulate",
      "f u c k",
      "f u c k e r",
      "f4nny",
      "fag",
      "fagging",
      "faggitt",
      "faggot",
      "faggs",
      "fagot",
      "fagots",
      "fags",
      "fanny",
      "fannyflaps",
      "fannyfucker",
      "fanyy",
      "fatass",
      "fcuk",
      "fcuker",
      "fcuking",
      "feck",
      "fecker",
      "felching",
      "fellate",
      "fellatio",
      "fingerfuck",
      "fingerfucked",
      "fingerfucker",
      "fingerfuckers",
      "fingerfucking",
      "fingerfucks",
      "fistfuck",
      "fistfucked",
      "fistfucker",
      "fistfuckers",
      "fistfucking",
      "fistfuckings",
      "fistfucks",
      "flange",
      "fook",
      "fooker",
      "fuck",
      "fucka",
      "fucked",
      "fucker",
      "fuckers",
      "fuckhead",
      "fuckheads",
      "fuckin",
      "fucking",
      "fuckings",
      "fuckingshitmotherfucker",
      "fuckme",
      "fucks",
      "fuckwhit",
      "fuckwit",
      "fudge packer",
      "fudgepacker",
      "fuk",
      "fuker",
      "fukker",
      "fukkin",
      "fuks",
      "fukwhit",
      "fukwit",
      "fux",
      "fux0r",
      "f_u_c_k",
      "gangbang",
      "gangbanged",
      "gangbangs",
      "gaylord",
      "gaysex",
      "goatse",
      "God",
      "god-dam",
      "god-damned",
      "goddamn",
      "goddamned",
      "hardcoresex",
      "hell",
      "heshe",
      "hoar",
      "hoare",
      "hoer",
      "homo",
      "hore",
      "horniest",
      "horny",
      "hotsex",
      "jack-off",
      "jackoff",
      "jap",
      "jerk-off",
      "jism",
      "jiz",
      "jizm",
      "jizz",
      "kawk",
      "knob",
      "knobead",
      "knobed",
      "knobend",
      "knobhead",
      "knobjocky",
      "knobjokey",
      "kock",
      "kondum",
      "kondums",
      "kum",
      "kummer",
      "kumming",
      "kums",
      "kunilingus",
      "l3i+ch",
      "l3itch",
      "labia",
      "lust",
      "lusting",
      "m0f0",
      "m0fo",
      "m45terbate",
      "ma5terb8",
      "ma5terbate",
      "masochist",
      "master-bate",
      "masterb8",
      "masterbat*",
      "masterbat3",
      "masterbate",
      "masterbation",
      "masterbations",
      "masturbate",
      "mo-fo",
      "mof0",
      "mofo",
      "mothafuck",
      "mothafucka",
      "mothafuckas",
      "mothafuckaz",
      "mothafucked",
      "mothafucker",
      "mothafuckers",
      "mothafuckin",
      "mothafucking",
      "mothafuckings",
      "mothafucks",
      "mother fucker",
      "motherfuck",
      "motherfucked",
      "motherfucker",
      "motherfuckers",
      "motherfuckin",
      "motherfucking",
      "motherfuckings",
      "motherfuckka",
      "motherfucks",
      "muff",
      "mutha",
      "muthafecker",
      "muthafuckker",
      "muther",
      "mutherfucker",
      "n1gga",
      "n1gger",
      "nazi",
      "nigg3r",
      "nigg4h",
      "nigga",
      "niggah",
      "niggas",
      "niggaz",
      "nigger",
      "niggers",
      "nob",
      "nob jokey",
      "nobhead",
      "nobjocky",
      "nobjokey",
      "numbnuts",
      "nutsack",
      "orgasim",
      "orgasims",
      "orgasm",
      "orgasms",
      "p0rn",
      "pawn",
      "pecker",
      "penis",
      "penisfucker",
      "phonesex",
      "phuck",
      "phuk",
      "phuked",
      "phuking",
      "phukked",
      "phukking",
      "phuks",
      "phuq",
      "pigfucker",
      "pimpis",
      "piss",
      "pissed",
      "pisser",
      "pissers",
      "pisses",
      "pissflaps",
      "pissin",
      "pissing",
      "pissoff",
      "poop",
      "porn",
      "porno",
      "pornography",
      "pornos",
      "prick",
      "pricks",
      "pron",
      "pube",
      "pusse",
      "pussi",
      "pussies",
      "pussy",
      "pussys",
      "rectum",
      "retard",
      "rimjaw",
      "rimming",
      "s hit",
      "s.o.b.",
      "sadist",
      "schlong",
      "screwing",
      "scroat",
      "scrote",
      "scrotum",
      "semen",
      "sex",
      "sh!+",
      "sh!t",
      "sh1t",
      "shag",
      "shagger",
      "shaggin",
      "shagging",
      "shemale",
      "shi+",
      "shit",
      "shitdick",
      "shite",
      "shited",
      "shitey",
      "shitfuck",
      "shitfull",
      "shithead",
      "shiting",
      "shitings",
      "shits",
      "shitted",
      "shitter",
      "shitters",
      "shitting",
      "shittings",
      "shitty",
      "skank",
      "slut",
      "sluts",
      "smegma",
      "smut",
      "snatch",
      "son-of-a-bitch",
      "spac",
      "spunk",
      "s_h_i_t",
      "t1tt1e5",
      "t1tties",
      "teets",
      "teez",
      "testical",
      "testicle",
      "tit",
      "titfuck",
      "tits",
      "titt",
      "tittie5",
      "tittiefucker",
      "titties",
      "tittyfuck",
      "tittywank",
      "titwank",
      "tosser",
      "turd",
      "tw4t",
      "twat",
      "twathead",
      "twatty",
      "twunt",
      "twunter",
      "v14gra",
      "v1gra",
      "vagina",
      "viagra",
      "vulva",
      "w00se",
      "wang",
      "wank",
      "wanker",
      "wanky",
      "whoar",
      "whore",
      "willies",
      "willy",
      "xrated",
      "xxx",
    ];
    let bad = true;
    for (let i = 0; i < badWords.length; i++) {
      // if user don't enter all the filds with appropriate words
      if (
        noun1txt == badWords[i] ||
        noun2txt == badWords[i] ||
        adj1txt == badWords[i] ||
        adj2txt == badWords[i] ||
        acttxt == badWords[i] ||
        verbtxt == badWords[i] ||
        occationtxt == badWords[i]
      ) {
        bad = true;
        break;
      }
      // if user enter all the filds with appropriate words
      else {
        bad = false;
      }
    }
    if (bad) {
      badMsg.textContent = "Please add appropriate words in the text filds.";
      errorr.classList.remove("hidden");
      overlayClick.classList.remove("hidden");
    } else {
      storyPara.classList.remove("hidden");
      enterWords.classList.add("hidden");
      // setting all the text fields
      noun1user.textContent = noun1txt;
      noun2user.textContent = noun2txt;
      adj1user.textContent = adj1txt;
      adj2user.textContent = adj2txt;
      actuser.textContent = acttxt;
      verbuser.textContent = verbtxt;
      occationuser.textContent = occationtxt;
    }
  }
});

btnCloseError.addEventListener("click", function () {
  errorr.classList.add("hidden");
  overlayClick.classList.add("hidden");
});

// declaring these arrays for the random button
// ==========================================================================declaring the adjectives=========================================================================================

const adjectives = [
  "aback",
  "abaft",
  "abandoned",
  "abashed",
  "aberrant",
  "tiny",
  "tired",
  "tiresome",
  "toothsome",
  "torpid",
  "tough",
  "towering",
  "tranquil",
  "trashy",
  "tremendous",
  "tricky",
  "trite",
  "troubled",
  "truculent",
  "true",
  "truthful",
  "two",
  "typical",
  "ubiquitous",
  "ugliest",
  "ugly",
  "ultra",
  "unable",
  "unaccountable",
  "unadvised",
  "unarmed",
  "unbecoming",
  "unbiased",
  "uncovered",
  "understood",
  "undesirable",
  "unequal",
  "unequaled",
  "uneven",
  "unhealthy",
  "uninterested",
  "unique",
  "unkempt",
  "unknown",
  "vivacious",
  "voiceless",
  "volatile",
  "voracious",
  "vulgar",
  "wacky",
  "waggish",
  "well-made",
  "well-off",
  "well-to-do",
  "wet",
  "whimsical",
  "whispering",
  "white",
  "whole",
  "wholesale",
  "wicked",
  "wide",
  "wide-eyed",
  "wiggly",
  "wild",
  "willing",
  "womanly",
  "wonderful",
  "wooden",
  "woozy",
  "workable",
  "worried",
  "worthless",
  "wrathful",
  "wretched",
  "wrong",
  "wry",
  "xenophobic",
  "yellow",
  "yielding",
  "young",
  "youthful",
  "yummy",
  "zany",
  "zealous",
  "zesty",
  "zippy",
  "zonked",
];
// ==========================================================================declaring the noun=========================================================================================
const nouns = [
  "accelerator",
  "accordion",
  "account",
  "accountant",
  "actress",
  "adapter",
  "addition",
  "address",
  "bar",
  "barbara",
  "bead",
  "beam",
  "bean",
  "bear",
  "chick",
  "chicken",
  "chicory",
  "chief",
  "child",
  "children",
  "input",
  "insect",
  "instruction",
  "instrument",
  "insulation",
  "insurance",
  "interactive",
  "join",
  "joke",
  "joseph",
  "journey",
  "keyboarding",
  "kick",
  "kidney",
  "kilogram",
  "kilometer",
  "kimberly",
  "kiss",
  "kitchen",
  "kite",
  "kitten",
  "lute",
  "luttuce",
  "lycra",
  "lynx",
  "lyocell",
  "lyre",
  "lyric",
  "macaroni",
  "machine",
  "macrame",
  "magazine",
  "magic",
  "magician",
  "maid",
  "mail",
  "mailbox",
  "mailman",
  "makeup",
  "malaysia",
  "male",
  "mall",
  "mallet",
  "man",
  "potato",
  "poultry",
  "pound",
  "powder",
  "power",
  "puppy",
  "purchase",
  "stopsign",
  "stopwatch",
  "store",
  "storm",
  "story",
  "stove",
  "swamp",
  "swan",
  "sweater",
  "sweatshirt",
  "sweatshop",
  "tub",
  "tuba",
  "tuesday",
  "tugboat",
  "tulip",
  "tuna",
  "tune",
  "turkey",
  "turkish",
  "turn",
  "turnip",
  "turnover",
  "turret",
  "turtle",
  "tv",
  "twig",
  "unshielded",
  "use",
  "utensil",
  "uzbekistan",
  "vacation",
  "vacuum",
  "valley",
  "value",
  "van",
  "var verbs = [aardvark",
  "vase",
  "vault",
  "vegetable",
  "vegetarian",
  "veil",
  "vein",
  "velvet",
  "venezuela",
  "venezuelan",
  "weed",
  "weeder",
  "week",
  "wind",
  "windchime",
  "winter",
  "wire",
  "wish",
  "witch",
  "withdrawal",
  "witness",
  "wolf",
  "woman",
  "women",
  "year",
  "yellow",
  "yew",
  "yogurt",
  "yoke",
  "yugoslavian",
  "zebra",
  "zephyr",
  "zinc",
  "zipper",
  "zone",
  "zoo",
  "zoology",
];
// ==========================================================================declaring the verb=========================================================================================

const verbs = [
  "accept",
  "add",
  "admire",
  "manage",
  "march",
  "mark",
  "marry",
  "match",
  "mate",
  "sparkle",
  "spell",
  "spill",
  "spoil",
  "spot",
  "spray",
  "sprout",
  "squash",
  "squeak",
  "squeal",
  "squeeze",
  "stain",
  "stamp",
  "stare",
  "start",
  "stay",
  "steer",
  "step",
  "stir",
  "stitch",
  "stop",
  "store",
  "strap",
  "strengthen",
  "stretch",
  "strip",
  "stroke",
  "tumble",
  "turn",
  "twist",
  "type",
  "undress",
  "unfasten",
  "unite",
  "unlock",
  "unpack",
  "untidy",
  "use",
  "vanish",
  "visit",
  "wail",
  "wait",
  "walk",
  "wander",
  "want",
  "warm",
  "warn",
  "wash",
  "wriggle",
  "x-ray",
  "yawn",
  "yell",
  "zip",
  "zoom",
];
// ==========================================================================declaring the activities=========================================================================================

const activities = [
  "Read to self",
  "Listen to reading",
  "Read to buddy",
  "Word work",
  "Work on writing",
  "Think–Pair–Share",
  "Case Studies and Problem-Based Learning",
  "Debate, Role Play",
  "Football",
  "Hockey",
  "Soccer",
  "Long-distance running",
  "Badminton",
  "Swimming",
  "Snowboarding",
  "Judo",
];
// ==========================================================================declaring the special days=========================================================================================

const universitySpecialDays = [
  "First day of classes",
  "Last day of classes",
  "Finals week",
  "Midterm exams",
  "Graduation day",
  "Homecoming",
  "Sports day",
  "Career fair",
  "Spring break",
  "Winter break",
  "Registration day",
  "Commencement ceremony",
  "Research symposium",
  "Alumni reunion",
  "Parent weekend",
  "Club fair",
];
// random button functionality
randombtn.addEventListener("click", function () {
  let randAdjective = Math.trunc(Math.random() * adjectives.length);
  let randAdjective2 = Math.trunc(Math.random() * adjectives.length);

  let randNoun = Math.trunc(Math.random() * nouns.length);
  let randNoun2 = Math.trunc(Math.random() * nouns.length);

  let randVerb = Math.trunc(Math.random() * verbs.length);
  let randActivities = Math.trunc(Math.random() * activities.length);
  let randSpacialDay = Math.trunc(Math.random() * universitySpecialDays.length);

  document.querySelector("#noun1").value = nouns[randNoun];
  document.querySelector("#noun2").value = nouns[randNoun2];
  document.querySelector("#adj1").value = adjectives[randAdjective];
  document.querySelector("#adj2").value = adjectives[randAdjective2];
  document.querySelector("#act").value = activities[randActivities];
  document.querySelector("#verb").value = verbs[randVerb];
  document.querySelector("#occation").value =
    universitySpecialDays[randSpacialDay];
});

// go back button functionality
backbtn.addEventListener("click", function () {
  clearAllInputs();
  enterWords.classList.remove("hidden");
  storyPara.classList.add("hidden");
});
